### ISSUE TITLE
After set Text Currency sign is not visible

### ISSUE THREAD

**Issue by pravin-umardand** [CottaCush/CurrencyEditText#14]
If we set value to Edit Text 
etPrice.setText("123")
then currency symbol is not visible. But its set in xml file like app:currencySymbol="$"

**Comment by pravin-umardand** [comment]
@efguydan Please update if bug is fixed?

**Comment by efguydan** [comment]
Yes @pravin-umardand. It has been fixed. Kindly update to version 0.0.7
