### ISSUE TITLE
Some amounts change while typing

### ISSUE THREAD

**Issue by akumaigorodski** [CottaCush/CurrencyEditText#29]
An example:

```
val amount = "515.809"
currencyEditText.setText(amount)
```

A text visible in a field is expected to be `515.809` and yet it becomes `515.808`. 
I get the same results when trying to enter `515.809` manually.

**Comment by akumaigorodski** [comment]
A bit more info: this does not happen on Xiaomi Mi 10 phone, but fails like this on Moto g(7) Power phone.

In both cases locale is set to `en_US` if this matters.

**Comment by efguydan** [comment]
Fixed by #32. Kindly update to version `0.0.10`
