### ISSUE TITLE
Jetpack Compose Support. 

### ISSUE THREAD

**Issue by rasheedsulayman** [CottaCush/CurrencyEditText#36]
Investigate how easy it is to support the `TextField` in Jetpack compose. Check if the formatting logic can be properly extracted and used for both the View-based EditText and Compose's `TextVField`. 

Ideally, the composing support should be exposed as an additional artefact/dependency on top of the core-library logic. We might need to do some refactoring on the existing package structure.

**Comment by efguydan** [comment]
Good idea. Let's check this. Visual Transformation / Actual Text Manipulation is something to check and decide on
And what data to expose as well.
