### ISSUE TITLE
decimal places

### ISSUE THREAD

**Issue by lpsistemas01** [CottaCush/CurrencyEditText#41]
it is not accepting decimal places. I click on the dot or comma and nothing happens, the number remains whole.

**Comment by efguydan** [comment]
Hello @lpsistemas01 , Can you add more details to this question?

Such as the Locale you are using & possibly a screen recording to help visualize this one. 

Thanks.

**Comment by CaiqueCoelho** [comment]
It's not working for pt-BR, for example, I couldn't make 27,38 where 38 is a decimal because I'm getting 2.378. In Brazil, we use commas for the decimals

**Comment by efguydan** [comment]
Hey @CaiqueCoelho , this bug is an EditText bug and unfortunately it hasn't been fixed. There are lot of workarounds by the community. I would recommend this one as it looks simplest. 

https://stackoverflow.com/a/16772758

```kotlin
 editText.keyListener = DigitsKeyListener.getInstance("0123456789.,") // You can customize the accepted keys you want.
```

Let me know if it helps. Thanks

**Comment by thtmorais** [comment]
> Hey @CaiqueCoelho , this bug is an EditText bug and unfortunately it hasn't been fixed. There are lot of workarounds by the community. I would recommend this one as it looks simplest.
> 
> https://stackoverflow.com/a/16772758
> 
> ```kotlin
>  editText.keyListener = DigitsKeyListener.getInstance("0123456789.,") // You can customize the accepted keys you want.
> ```
> 
> Let me know if it helps. Thanks

It's work for pt-BR!!!

**Comment by efguydan** [comment]
Great to hear. 
Closing this one
