### ISSUE TITLE
Configure Renovate to handle Automatic dependency updates

### ISSUE THREAD

**Issue by efguydan** [CottaCush/CurrencyEditText#42]

**Comment by rasheedsulayman** [comment]
Would Renovate propose the dependency update as a PR, or directly make the change? 
I guess the former. I'm a bit on the conservative side with dependencies. We should manually merge the updates to not silently break things.

**Comment by efguydan** [comment]
Yes, It would propose the updates as Pull Requests. 
The pipeline would also run for those PRs so if they pass, there will be some confidence in them.

You can check the current PR it would create in #44.
It will start creating them as soon as that's merged. I just want to configure how it should group them first.
