### ISSUE TITLE
Display blank in the EditText

### ISSUE THREAD

**Issue by tcqq** [CottaCush/CurrencyEditText#8]
First, focus in front of the currency selected symbol
![TIM图片20200217095717](https://user-images.githubusercontent.com/10644057/74618331-33775d80-516c-11ea-90a3-6ecb94dac5dd.png)

Then enter the number 1, 2
![TIM图片20200217095722](https://user-images.githubusercontent.com/10644057/74618368-628dcf00-516c-11ea-862c-0b5945b38fb8.png)![InkedTIM图片20200217095725_LI](https://user-images.githubusercontent.com/10644057/74618499-05464d80-516d-11ea-9f95-e49b8838a365.png)

Will be displayed blank in the EditText and the cursor is not displayed in front of the text. @codedentwickler

**Comment by mitsinsar** [comment]
@tcqq I've opened PR about this. You can check, fork, and fix it until PR is merged
https://github.com/CottaCush/CurrencyEditText/pull/11

**Comment by tcqq** [comment]
@mitsinsar Thank you.

**Comment by efguydan** [comment]
Fixed by #11. closing this.
